public class New32 {
    
  /*   public String clientName;
        public string website;
        public string email;
        public long phone;
    
   private list<Client> customers=new list<Client>();
    public void addNewCustomer(String clientName,string website,string email,long phone){
       New32 c =new New32(clientName,website,email,phone);
        customers.add(c);
    }
    private class Client{
        public String clientName;
        public string website;
        public string email;
        public long phone;
        
        Client(String clientName,string website,string email,long phone){
            clientName=clientName;
            website=website;
            email=email;
            phone=phone;
        }
    }
    public void getCustomers(){
        for(Client crr:Customers){
            System.debug(crr.clientName);
        }
    }*/
}